### PR TITLE
pvl application to PlanetaryPy

### PR DESCRIPTION
**Pull request by rbeyer**

### CODE REVIEW

**Comment by michaelaye** [comment]
Because I need to fill in values as a reviewer here, I'm unsure how to do it technically. Am I supposed to edit the PR directly?

**Comment by rbeyer** [comment]
Yes, the [procedure](https://github.com/planetarypy/TC/blob/master/Procedures/Affiliated-Package-Review-Process.md#reviewing-affiliated-packages) indicates that after the coordinator has their review completed, they add it to this PR discussion thread, and then edit the PR so that values in the PR are consistent with the posted review.

**Comment by michaelaye** [comment]
I don't know if there is another reviewer assigned?

This package has been reviewed for inclusion in the PlanetaryPy affiliated package
ecosystem by myself, and I have
synthesized the results of the review here.

You can find out more about our review criteria in
[Reviewing affiliated packages](https://github.com/planetarypy/TC/blob/master/Procedures/Affiliated-Package-Review-Guidelines.md).
For each of the review categories below we have listed the score and have
included some comments when the score is not green.

*Remove the badges that aren't needed:*

<table>
<tr><td><b>Functionality/Scope</b></td><td>
<a href="https://github.com/planetarypy/TC/blob/master/Procedures/Affiliated-Package-Review-Guidelines.md#Functionality-functionality">
General package
</a></td></tr>

<tr><td colspan=2><i>No further comments</i></td></tr>

<tr><td><b>Integration with PlanetaryPy ecosystem</b></td><td>
<a href="https://github.com/planetarypy/TC/blob/master/Procedures/Affiliated-Package-Review-Guidelines.md#Integration-with-the-PlanetaryPy-ecosystem-`ecointegration`">
Green
</a></td></tr>

<tr><td colspan=2><i>No further comments</i></td></tr>

<tr><td><b>Documentation</b></td><td>
<a href="https://github.com/planetarypy/TC/blob/master/Procedures/Affiliated-Package-Review-Guidelines.md#Documentation-documentation">
Green
</a></td></tr>

<tr><td colspan=2><i>No further comments</i></td></tr>

<tr><td><b>Testing</b></td><td>
<a href="https://github.com/planetarypy/TC/blob/master/Procedures/Affiliated-Package-Review-Guidelines.md#Testing-testing">
Green
</a></td></tr>

<tr><td colspan=2><i>No further comments</i></td></tr>

<tr><td><b>Development status</b></td><td>
<a href="https://github.com/planetarypy/TC/blob/master/Procedures/Affiliated-Package-Review-Guidelines.md#Development-status-devstatus">
Green
</a></td></tr>

<tr><td colspan=2><i>No further comments</i></td></tr>

<tr><td><b>Python version compatibility</b></td><td>
<a href="https://github.com/planetarypy/TC/blob/master/Procedures/Affiliated-Package-Review-Guidelines.md##Python-vertion-compatibility-pythonver">
Green
</a></td></tr>

<tr><td colspan=2><i>No further comments</i></td></tr>

</table>

*Other comments here*


*If accepted and there are no governance documents or only partial governance documents:*
Please remember that if your package doesn't explicitly have a set
of governance documents, that's fine!  The PlanetaryPy Project's
governance models (consensus seeking, code of conduct, etc.)
automatically apply to your project.  If you want something different,
be sure to include it in your package.

*If accepted with all green:*

**Summary/Decision**: Everything looks great, and we're happy to confirm that
this package is accepted as an affiliated package! :trophy:

*If accepted with some orange:*

**Summary/Decision**: This package meets the review criteria for affiliated
packages, so we are happy to confirm that we'll be listing your package as an
affiliated package! Keep up the good work, and we encourage you to improve on
the areas above that weren't "green" yet.

*If there is any red:*

**Summary/Decision**: Thanks for your work on this package! At the moment, we
found some issues in some of the review areas. As per the review guidelines, we
therefore won't be able to accept this package as an affiliated package yet.
We will leave this pull request open for a month in case you would like to
respond to the comments and/or address any of them.

*In all cases:*

If you have any follow-up questions or disagree with any of the comments above,
leave a comment and we can discuss it here. At any point in future you can
request a re-review of the package if you believe any of the scores should be
updated - contact the coordination committee, and we’ll do a new review.

**Comment by michaelaye** [comment]
email invite for review sent.

**Comment by michaelaye** [comment]
Jesse's review received on Sep 21 (sorry!)

**Comment by michaelaye** [comment]
Now, for realz:

This package has been reviewed for inclusion in the PlanetaryPy affiliated package
ecosystem by Jesse Mapel and myself, and I have
synthesized the results of the review here.

You can find out more about our review criteria in
[Reviewing affiliated packages](https://github.com/planetarypy/TC/blob/master/Procedures/Affiliated-Package-Review-Guidelines.md).
For each of the review categories below we have listed the score and have
included some comments when the score is not green.

<table>
<tr><td><b>Functionality/Scope</b></td><td>
<a href="https://github.com/planetarypy/TC/blob/master/Procedures/Affiliated-Package-Review-Guidelines.md#Functionality-functionality">
General package
</a></td></tr>

<tr><td colspan=2><i>The PDS is the primary archival data source for all planetary, satellite based
data sets. The vast majority of data sets use the PDS 3 standard which uses PVL
for its labels. For this reason, PVL is useful for anyone who wants to work with
data from the PDS.</i></td></tr>

<tr><td><b>Integration with PlanetaryPy ecosystem</b></td><td>
<a href="https://github.com/planetarypy/TC/blob/master/Procedures/Affiliated-Package-Review-Guidelines.md#Integration-with-the-PlanetaryPy-ecosystem-`ecointegration`">
N/A
</a></td></tr>

<tr><td colspan=2><i>As this is a very low level package that doesn't have any dependencies, we do not believe it makes sense to evaluate this package for how well it uses other packages in the ecosystem. </i></td></tr>

<tr><td><b>Documentation</b></td><td>
<a href="https://github.com/planetarypy/TC/blob/master/Procedures/Affiliated-Package-Review-Guidelines.md#Documentation-documentation">
Green
</a></td></tr>

<tr><td colspan=2><i>The documentation is very robust and has everything from simple tutorials to
complex explanation of submodules and specifications.</i></td></tr>

<tr><td><b>Testing</b></td><td>
<a href="https://github.com/planetarypy/TC/blob/master/Procedures/Affiliated-Package-Review-Guidelines.md#Testing-testing">
Green
</a></td></tr>

<tr><td colspan=2><i>Test coverage looks good, but is not evaluated programmatically. CI runs on both
the main branch and all PRs. Overall, testing is very high quality and seems to
explore the entirety of the different PVL specifications.</i></td></tr>

<tr><td><b>Development status</b></td><td>
<a href="https://github.com/planetarypy/TC/blob/master/Procedures/Affiliated-Package-Review-Guidelines.md#Development-status-devstatus">
Green
</a></td></tr>

<tr><td colspan=2><i>The package is actively being developed and just recently released 1.0</i></td></tr>

<tr><td><b>Python version compatibility</b></td><td>
<a href="https://github.com/planetarypy/TC/blob/master/Procedures/Affiliated-Package-Review-Guidelines.md##Python-vertion-compatibility-pythonver">
Green
</a></td></tr>

<tr><td colspan=2><i>Current releases are available for 3.6 and later.</i></td></tr>

</table>

**Summary/Decision**: Everything looks great, and we're happy to confirm that
this package is accepted as an affiliated package! :trophy:

If you have any follow-up questions or disagree with any of the comments above,
leave a comment and we can discuss it here. At any point in future you can
request a re-review of the package if you believe any of the scores should be
updated - contact the coordination committee, and we’ll do a new review.

**Review by AndrewAnnex — APPROVED** [review]

**Review by cmillion — APPROVED** [review]

**Pull request merged**
