### PR TITLE
Draft agenda for May meeting.

### PR DESCRIPTION
**Pull request by rbeyer**

### CODE REVIEW

**Review by michaelaye — APPROVED** [review]

**Comment by AndrewAnnex** [comment]
I actually cannot attend this meeting due to a conflict (I am unavailable Tuesday-Thursday that week), would it be possible to move a day earlier?

**Comment by michaelaye** [comment]
I am fully booked on Monday, sorry. 
Michael

**Comment by rbeyer** [comment]
Should we push to Friday (28th)?

**Comment by michaelaye** [comment]
That works for me.

**Comment by rbeyer** [comment]
@AndrewAnnex, if Friday works for you, please approve this PR.

**Review by AndrewAnnex — APPROVED** [review]

**Pull request merged**
