### PR TITLE
Draft agenda for December meeting.

### PR DESCRIPTION
**Pull request by rbeyer**

### CODE REVIEW

**Review by AndrewAnnex — APPROVED** [review]
although this is during agu it looks like nothing serious overlaps on my schedule, so as long as we keep it quick it shouldn't be a problem for me

**Comment by michaelaye** [comment]
Unfortunately the embassy scheduled my new passport appointment right on top of this.
I sadly must report that I cannot setup the pypi GH workflow for `pvl` as I lost my access to my pypi account. How, you ask? Setting up 2FA WITHOUT storing recovery codes (the system did not enforce that) and then having an iPhone system wipe removing my 2FA setup (and Google authenticator doesn't store the setup anywhere, Authy is better that way).
On top of that, Pypi is being overwhelmed with people that have similar failure stories, needing account recovery, and their volunteer time cannot handle it: https://github.com/pypa/pypi-support/issues/679

**Comment by michaelaye** [comment]
In general, FYI, i am slowly developing a working schedule with the baby, so should become more active again soon.

**Comment by rbeyer** [comment]
I think we need @michaelaye for most of the agenda items, and we skipped last month's meeting.  I think we need to meet before January.  Does pushing to next Tuesday (Dec 22) at the same time work?

**Comment by cmillion** [comment]
Dec 22 works for me.

**Comment by AndrewAnnex** [comment]
Sure, also I recommend using yubikeys and a safety deposit box going forward ;)

-Andrew Annex

**Comment by michaelaye** [comment]
works here. No yubikeys offered by pypi login system.

**Comment by AndrewAnnex** [comment]
??? Yubikeys are physical usb security tokens for 2FA and there are plenty of tutorials on how to set them up with pypi. See https://www.yubico.com/ and https://pypi.org/help/#totp



-Andrew Annex

**Comment by ewdurbin** [comment]
> works here. No yubikeys offered by pypi login system.

PyPI Does support Yubikeys via WebAuth, see https://pypi.org/help/#utfkey

**Comment by AndrewAnnex** [comment]
Is there someone else with ownership/admin rights of PVL on pypi to add more people? I could go ahead and set this up as I recently transitioned spiceypy to use github actions and pypi tokens

**Comment by rbeyer** [comment]
> Is there someone else with ownership/admin rights of PVL on pypi to add more people? I could go ahead and set this up as I recently transitioned spiceypy to use github actions and pypi tokens

In addition to the grandfathered maintainers, @michaelaye and I have maintainer access to the PyPI pvl project.  If you don't mind, I'd love to talk about this at our meeting next week, and then maybe chat with you @AndrewAnnex and set it up so I can learn how to do it.

**Comment by AndrewAnnex** [comment]
Sounds good!

-Andrew Annex

**Pull request merged**
