### PR TITLE
kalasiris application to PlanetaryPy

### PR DESCRIPTION
**Pull request by rbeyer**

### CODE REVIEW

**Comment by AndrewAnnex** [comment]
the 1st external reviewer declined to review kalasiris. Waiting to hear from the alternate.

**Comment by AndrewAnnex** [comment]
_\*updated with anonymous reviewer comments 05/21/2021\*_
_\*updated testing score 05/22/2021\*_
This package has been reviewed for inclusion in the PlanetaryPy affiliated package
ecosystem by a member of the PlanetaryPy community as well as myself, and I have
synthesized the results of the review here.

You can find out more about our review criteria in
[Reviewing affiliated packages](https://github.com/planetarypy/TC/blob/master/Procedures/Affiliated-Package-Review-Guidelines.md).
For each of the review categories below we have listed the score and have
included some comments when the score is not green.

<table>
<tr><td><b>Functionality/Scope</b></td><td>
<a href="https://github.com/planetarypy/TC/blob/master/Procedures/Affiliated-Package-Review-Guidelines.md#Functionality-functionality">
General package
</a></td></tr>

<tr><td colspan=2><i><p>Anonymous reviewer stated that kalasiris did not provided enough added value over pysis or bash scripting for them personally. </p> Review coordinator notes that review guidelines are broadly defined, and notes the potential of added-value capabilities.  </i></td></tr>

<tr><td><b>Integration with PlanetaryPy ecosystem</b></td><td>
<a href="https://github.com/planetarypy/TC/blob/master/Procedures/Affiliated-Package-Review-Guidelines.md#Integration-with-the-PlanetaryPy-ecosystem-`ecointegration`">
Good
</a></td></tr>

<tr><td colspan=2><i><p>Anonymous reviewer pointed out the existence of pysis causing kalasiris to potentially be in conflict with the objective of ecointegration. Anonymous reviewer goes on to note the lack of an established user base for kalasiris relative to pysis. Anonymous reviewer however also noted the lack of activity on pysis, and that kalasiris stands a better chance of being developed further, justifying approval to the reviewer.</p> Review coordinator notes that pysis is not currently affiliated with planetarypy, so kalasiris meets the definition of establishing base functionality in the planetarypy ecosystem specifically. </i></td></tr>

<tr><td><b>Documentation</b></td><td>
<a href="https://github.com/planetarypy/TC/blob/master/Procedures/Affiliated-Package-Review-Guidelines.md#Documentation-documentation">
Good
</a></td></tr>

<tr><td colspan=2><i> Review coordinator: I think more examples in the documentation outside of the quickstart could demonstrate the additional benefits/features of kalasiris such as `k_funcs` more visibly to new users.</i></td></tr>

<tr><td><b>Testing</b></td><td>
<a href="https://github.com/planetarypy/TC/blob/master/Procedures/Affiliated-Package-Review-Guidelines.md#Testing-testing">
Good
</a></td></tr>

<tr><td colspan=2><i> No further comments</i></td></tr>

<tr><td><b>Development status</b></td><td>
<a href="https://github.com/planetarypy/TC/blob/master/Procedures/Affiliated-Package-Review-Guidelines.md#Development-status-devstatus">
Good
</a></td></tr>

<tr><td colspan=2><i>No further comments</i></td></tr>

<tr><td><b>Python version compatibility</b></td><td>
<a href="https://github.com/planetarypy/TC/blob/master/Procedures/Affiliated-Package-Review-Guidelines.md##Python-vertion-compatibility-pythonver">

</a></td></tr>

<tr><td colspan=2><i>No further comments</i></td></tr>

</table>

**Summary/Decision**: This package meets the review criteria for affiliated
packages, so we are happy to confirm that we'll be listing your package as an
affiliated package! Keep up the good work, and we encourage you to improve on
the areas above that weren't "green" yet.


If you have any follow-up questions or disagree with any of the comments above,
leave a comment and we can discuss it here. At any point in future you can
request a re-review of the package if you believe any of the scores should be
updated - contact the coordination committee, and we’ll do a new review.

**Comment by rbeyer** [comment]
I have added Codecov to the project's GitHub workflow, and test coverage is now being updated a reported with each push.

**Comment by AndrewAnnex** [comment]
testing review has been updated to reflect changes

**Comment by AndrewAnnex** [comment]
Also, anonymous reviewer supplied general comments that have been amended to the review

**Review by AndrewAnnex — APPROVED** [review]
approved!

**Review by michaelaye — APPROVED** [review]

**Pull request merged**
